# PARA ARMAZENAR OS DADOS INICIALMENTE USAMOS UMA LISTA E MAIS TARDE PASSAREMOS PARA UMA BASE DE DADOS
# CRIAMOS A LISTA DAS LOJAS, E DENTRO DA LISTA VAMOS TER DICIONÁRIOS (UM POR LOJA) E CADA UM TERÁ O NOME DA LOJA E UMA LISTA DE ITENS
# DENTRO DE CADA LISTA DE ITENS IRÁ EXISTIR DICIONÁRIOS PARA CADA ITEM (COMO O NOME E O PREÇO DO ITEM)

# NO VIDEO DA CRIAÇÃO DESTE FICHEIRO "db.py" PASSÁMOS DE TER LISTAS PARA OS ITENS E LOJAS, A TER DICIONÁRIOS. A VANTAGEM DISTO 
# É QUE AGORA CONSEGUIMOS PROCURAR OS ITENS OU LOJAS PELOS SEUS ID's

""" ANTES DA CRIAÇÃO DA BASE DE DADOS UTILIZAVA-SE ESTE CÓDIGO PARA ARMAZENAR OS DADOS (ATÉ À SECÇÃO 6) DEPOIS DA SECÇÃO 6 ESTE CÓDIGO NÃO SE USA MAIS

stores = {}
items = {
    1: {
        "name" : "Chair",
        "price": 17.99
    },
    2: {
        "name": "Table",
        "price": 180.50
    }
}
"""

from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy() # CRIA O OBJETO SQLAlchemy A PARTIR DA EXTENSÃO flask_sqlalchemy PARA PODERMOS LIGÁ-LO À NOSSA APLICAÇÃO FLASK
